services:

  consul:
    image: hashicorp/consul:1.19
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8501"
      - "8600:8600/udp"
    volumes:
      - ./Infrastructure/consul/consul-config.json:/consul/config/consul-config.json:ro
      - ./Infrastructure/certs:/certs:ro
    command: consul agent -config-file=/consul/config/consul-config.json -client=0.0.0.0
    networks:
      - dotnet-case-study-net

  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_pass
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    networks:
      - dotnet-case-study-net

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - postgres-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - dotnet-case-study-net
      
  gateway:
    build:
      context: .
      dockerfile: Edge/Gateway.Yarp/Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./Infrastructure/certs:/certs:ro
    environment:
      ASPNETCORE_URLS: http://+:5000
      Mtls__GatewayCertPassword: gateway123
    depends_on:
      - consul
      - keycloak
    networks:
      - dotnet-case-study-net
        
  sentinel-service:
    build:
      context: .
      dockerfile: Application/SentinelService/Dockerfile
    container_name: sentinel-service
    restart: unless-stopped
    ports:
      - "5001:5001"
      - "5011:5011"
    environment:
      ASPNETCORE_URLS: http://+:5001;https://+:5011
      Consul__Host: https://consul:8501
      Consul__ServiceAddress: sentinel-service
      Consul__ServicePort: 5011
      Keycloak__ClientSecret: cGe2CVCkRUQeb3jxalvBuci4Ub4Utiym
      Mtls__ServiceCertPassword: sentinel123
    depends_on:
      - consul
    networks:
      - dotnet-case-study-net
    volumes:
      - ./Infrastructure/certs:/certs:ro
    
  audit-service:
    build:
      context: .
      dockerfile: Application/AuditService/Dockerfile
    container_name: audit-service
    restart: unless-stopped
    ports:
      - "5002:5002"
      - "5012:5012"
    environment:
      ASPNETCORE_URLS: http://+:5002;https://+:5012
      Consul__Host: https://consul:8501
      Consul__ServiceAddress: audit-service
      Consul__ServicePort: 5012
      Mtls__ServiceCertPassword: audit123
    depends_on:
      - consul
    networks:
      - dotnet-case-study-net
    volumes:
      - ./Infrastructure/certs:/certs:ro

networks:
  dotnet-case-study-net:
    driver: bridge

volumes:
  postgres-keycloak-data: